const SPREADSHEET_ID='1eOWiWZh0zTnVLnv53bTDXvlFJJG5ZbvR6Upr7_9uLb8';
const ORDERS_SHEET='ORDENES',EXPENSES_SHEET='GASTOS',PRODUCTS_SHEET='PRODUCTOS',CONFIG_SHEET='CONFIGURACION',INVENTORY_SHEET='INVENTARIO';
const LOGO_FILE_ID='1KNCCBhFm4vD92Jpi5rdKKgC6xxEWk1ea';
const APP_CACHE_KEY='PRINTA_APP_DATA_V11';
const ORDER_HEADERS=['ID','FECHA','ESTADO','ORIGEN','CLIENTE','PRODUCTO','CANTIDAD','NOTAS','PAGADO','FECHA_ENVIO','FOTO','CREADO_EN','ACTUALIZADO_EN','COSTO_TOTAL','GANANCIA','INVENTARIO_DESCONTADO','MATERIALES_JSON','OTROS_COSTOS_JSON'];
const EXPENSE_HEADERS=['ID','FECHA','CATEGORIA','LUGAR','CANTIDAD','NOTA','RECIBO','CREADO_EN'];
const PRODUCT_HEADERS=['ID','NOMBRE','FOTO','DISPONIBLE','CREADO_EN','ACTUALIZADO_EN'];
const INVENTORY_HEADERS=['ID','NOMBRE','CATEGORIA','CANTIDAD','COSTO_TOTAL','COSTO_UNITARIO','NOTA','CREADO_EN','ACTUALIZADO_EN'];

function doGet(){
  ensureSchema_();
  let html=HtmlService.createTemplateFromFile('App').evaluate().getContent();
  const icon=getLogoDataUrl();
  html=html.replace('</head>',`<link rel="icon" type="image/png" href="${icon}"><style>
  .order>.gallery{display:none!important}.costline{display:flex;justify-content:space-between;gap:10px;margin-top:7px;padding-top:7px;border-top:1px dashed #ddd;font-size:13px}.gain{color:#15803d;font-weight:900}.loss{color:#dc2626;font-weight:900}.stock-pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef2ff;color:#5b21b6;font-size:12px;font-weight:900;margin:4px 4px 0 0}.stock-pill.low{background:#fee2e2;color:#b91c1c}.material-row{display:grid;grid-template-columns:1fr 110px auto;gap:8px;align-items:end;margin:8px 0}.other-row{display:grid;grid-template-columns:1fr 130px auto;gap:8px;align-items:end;margin:8px 0}.inventory-box{padding:14px;border:1px solid #e7e7ef;border-radius:14px;background:#fafaff}.btn.saving{position:relative;color:transparent!important;pointer-events:none}.btn.saving:after{content:'';position:absolute;left:50%;top:50%;width:18px;height:18px;margin:-11px 0 0 -11px;border:3px solid #ffffff66;border-top-color:#fff;border-radius:50%;animation:spinP .65s linear infinite}@keyframes spinP{to{transform:rotate(360deg)}}@media(max-width:560px){.material-row,.other-row{grid-template-columns:1fr 85px auto}.tabs{grid-template-columns:repeat(5,1fr)!important}.tabs button{font-size:12px!important;padding:10px 3px!important}}
  </style></head>`);
  html=html.replace(/function due\(o\)\{.*?\}function photoUrls/,`function due(o){if(o.estado==='Listo')return'Orden lista';const d=dateObj(o.fechaEnvio);if(!d)return'Fecha de entrega pendiente';const n=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];return'Entregar antes del '+n[d.getDay()]}function photoUrls`);
  html=html.replace(/function card\(o\)\{.*?\}function orders/,`function card(o){const g=num(o.ganancia),c=num(o.costoTotal);return\`<div class="card order \${color(o)}"><div class="top"><span class="badge \${o.estado==='Listo'?'ready':''}">\${esc(o.estado)}</span><span class="origin">\${esc(o.origen)}</span></div><h3>\${esc(o.cliente)}</h3><p><b>\${esc(o.producto)}</b> × \${esc(o.cantidad)}</p><p>Pagado: <b>\${money(o.pagado)}</b></p><div class="costline"><span>Costo: <b>\${money(c)}</b></span><span class="\${g>=0?'gain':'loss'}">\${g>=0?'+':''}\${money(g)}</span></div><div class="deadline">\${due(o)}</div>\${o.notas?\`<p>\${esc(o.notas)}</p>\`:''}<div class="actions"><button class="btn good" onclick="statusFast('\${o.id}','\${o.estado==='Listo'?'Pendiente':'Listo'}',this)">\${o.estado==='Listo'?'Regresar a pendiente':'✅ Listo'}</button><button class="btn light" onclick="editFast('\${o.id}',this)">Editar</button><button class="btn danger" onclick="removeFast('\${o.id}',this)">Eliminar</button></div></div>\`}function orders`);
  html=html.replace(/async function submitOrder\(e\)\{.*?\}async function submitExpense/,orderSubmitClient_()+'async function submitExpense');
  html=html.replace(/function status\(id,s\)\{.*?\}function removeOrder\(id\)\{.*?\}function removeExpense/,fastButtonsClient_()+'function removeExpense');
  html=html.replace('</body>',inventoryClient_()+'</body>');
  return HtmlService.createHtmlOutput(html).setTitle('PRINTA').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function orderSubmitClient_(){return `async function submitOrder(e){e.preventDefault();const f=e.target,b=f.querySelector('button[type="submit"],button:not([type])'),start=Date.now(),o=Object.fromEntries(new FormData(f).entries());o.cliente=String(f.elements.cliente.value||'').trim();o.producto=String(f.elements.producto.value||'').trim();if(!o.cliente||!o.producto){const x=$('#orderError');x.textContent='Completa cliente y producto.';x.style.display='block';return}const isEdit=String($('#orderTitle').textContent||'').toLowerCase().includes('editar')&&String(o.id||'').trim();o._mode=isEdit?'edit':'create';o.clientKey=isEdit?'':('CLIENT-'+Date.now()+'-'+Math.random().toString(36).slice(2,10));if(!isEdit)o.id='';o.materialesJson=JSON.stringify(window.printaMaterials||[]);o.otrosCostosJson=JSON.stringify(window.printaOtherCosts||[]);setButtonSpin(b,true);const backup=JSON.parse(JSON.stringify(data));try{const visualId=isEdit?o.id:('PC-'+o.clientKey),old=photoUrls(o.foto),fresh=[];for(const file of pendingFiles)fresh.push(await upload(file,visualId,'orden'));o.foto=[...old,...fresh].join('|||');data=await retryServer('saveOrder',[o]);await waitMinimum(start,500);pendingFiles=[];render();closeModal('orderModal');setButtonSpin(b,false)}catch(err){data=backup;render();setButtonSpin(b,false);showModal('orderModal');const x=$('#orderError');x.textContent=err&&err.message?err.message:'No se pudo guardar.';x.style.display='block'}}`}
function fastButtonsClient_(){return `function setButtonSpin(b,on){if(!b)return;if(on){b.classList.add('saving');b.disabled=true}else{b.classList.remove('saving');b.disabled=false}}function waitMinimum(s,m){return new Promise(r=>setTimeout(r,Math.max(0,m-(Date.now()-s))))}function serverCall(fn,args){return new Promise((ok,no)=>{const r=google.script.run.withSuccessHandler(ok).withFailureHandler(no);r[fn].apply(r,args)})}async function retryServer(fn,args){let e;for(let i=0;i<3;i++){try{return await serverCall(fn,args)}catch(x){e=x;if(i<2)await new Promise(r=>setTimeout(r,450*(i+1)))}}throw e}async function statusFast(id,s,b){const backup=JSON.parse(JSON.stringify(data));setButtonSpin(b,true);try{data=await retryServer('setOrderStatus',[id,s]);render()}catch(e){data=backup;render();alert(e.message||e)}setButtonSpin(b,false)}async function editFast(id,b){setButtonSpin(b,true);await waitMinimum(Date.now(),500);setButtonSpin(b,false);editOrder(id)}async function removeFast(id,b){if(!confirm('¿Eliminar esta orden?'))return;const backup=JSON.parse(JSON.stringify(data));setButtonSpin(b,true);try{data=await retryServer('deleteOrder',[id]);render()}catch(e){data=backup;render();alert(e.message||e)}setButtonSpin(b,false)}`}

function inventoryClient_(){return `<script>(function(){
window.printaMaterials=[];window.printaOtherCosts=[];
function installInventoryUI(){
 const tabs=document.querySelector('.tabs');if(tabs&&!document.querySelector('[data-inventory-tab]'))tabs.insertAdjacentHTML('beforeend','<button data-inventory-tab onclick="showTab(\'inventario\',this);renderInventory()">Inventario</button>');
 const wrap=document.querySelector('.wrap');if(wrap&&!document.querySelector('#inventario'))wrap.insertAdjacentHTML('beforeend','<section id="inventario" class="section"><div class="toolbar"><h2>Inventario</h2><button class="btn primary" onclick="openInventoryModal()">+ Agregar inventario</button></div><div class="products" id="inventoryList"></div></section>');
 if(!document.querySelector('#inventoryModal'))document.body.insertAdjacentHTML('beforeend','<div id="inventoryModal" class="modal"><div class="panel"><div class="panel-head"><h2>Agregar inventario</h2><button class="x" onclick="closeModal(\'inventoryModal\')">×</button></div><div id="inventoryError" class="error"></div><form id="inventoryForm" class="form" onsubmit="saveInventoryItemClient(event)"><div><label>Nombre</label><input name="nombre" required></div><div><label>Categoría</label><select name="categoria"><option>Producto</option><option>Embalaje</option><option>Hoja</option><option>Tinta</option><option>Material</option><option>Otro</option></select></div><div><label>Cantidad comprada</label><input name="cantidad" type="number" min="0.01" step="0.01" required></div><div><label>Total pagado</label><input name="costoTotal" type="number" min="0" step="0.01" required></div><div class="full"><label>Nota</label><textarea name="nota"></textarea></div><div class="full actions"><button class="btn primary">Guardar</button><button type="button" class="btn light" onclick="closeModal(\'inventoryModal\')">Cancelar</button></div></form></div></div>');
 const orderActions=document.querySelector('#orderForm .actions');if(orderActions&&!document.querySelector('#orderMaterialsBox'))orderActions.insertAdjacentHTML('beforebegin','<div id="orderMaterialsBox" class="full inventory-box"><div class="toolbar" style="margin:0 0 8px"><h3>Materiales de esta orden</h3><button type="button" class="btn light" onclick="addMaterialRow()">+ Material</button></div><div id="materialRows"></div><div class="toolbar" style="margin:12px 0 8px"><h3>Otros costos</h3><button type="button" class="btn light" onclick="addOtherCostRow()">+ Otro costo</button></div><div id="otherCostRows"></div><div class="costline"><span>Costo total: <b id="orderCostPreview">$0.00</b></span><span id="orderProfitPreview" class="gain">+$0.00</span></div></div>');
}
window.openInventoryModal=function(){const f=document.querySelector('#inventoryForm');f.reset();document.querySelector('#inventoryError').style.display='none';showModal('inventoryModal')};
window.saveInventoryItemClient=function(e){e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f).entries());f.classList.add('loading');google.script.run.withSuccessHandler(d=>{data=d;f.classList.remove('loading');closeModal('inventoryModal');renderInventory()}).withFailureHandler(x=>{f.classList.remove('loading');const z=document.querySelector('#inventoryError');z.textContent=x.message||x;z.style.display='block'}).saveInventoryItem(o)};
window.renderInventory=function(){const el=document.querySelector('#inventoryList');if(!el)return;const a=data.inventory||[];el.innerHTML=a.length?a.map(x=>'<div class="card"><h3>'+esc(x.nombre)+'</h3><span class="stock-pill '+(num(x.cantidad)<=2?'low':'')+'">Disponible: '+num(x.cantidad)+'</span><span class="stock-pill">Unidad: '+money(x.costoUnitario)+'</span><p>'+esc(x.categoria||'Material')+(x.nota?' · '+esc(x.nota):'')+'</p><button class="btn danger" onclick="deleteInventoryClient(\''+x.id+'\')">Eliminar</button></div>').join(''):'<div class="empty">No hay artículos en inventario.</div>'};
window.deleteInventoryClient=function(id){if(!confirm('¿Eliminar este artículo?'))return;google.script.run.withSuccessHandler(d=>{data=d;renderInventory()}).withFailureHandler(x=>alert(x.message||x)).deleteInventoryItem(id)};
function options(sel){return '<option value="">Seleccionar</option>'+((data.inventory||[]).map(x=>'<option value="'+esc(x.id)+'">'+esc(x.nombre)+' ('+num(x.cantidad)+')</option>').join(''))}
window.addMaterialRow=function(item){const id='mr'+Date.now()+Math.random().toString(36).slice(2,5),m=item||{id:'',cantidad:1};document.querySelector('#materialRows').insertAdjacentHTML('beforeend','<div class="material-row" id="'+id+'"><div><label>Material</label><select onchange="syncMaterials()">'+options()+'</select></div><div><label>Cantidad</label><input type="number" min="0.01" step="0.01" value="'+num(m.cantidad||1)+'" oninput="syncMaterials()"></div><button type="button" class="btn danger" onclick="this.parentElement.remove();syncMaterials()">×</button></div>');const row=document.querySelector('#'+id);row.querySelector('select').value=m.id||'';syncMaterials()};
window.addOtherCostRow=function(item){const x=item||{nombre:'',costo:0};document.querySelector('#otherCostRows').insertAdjacentHTML('beforeend','<div class="other-row"><div><label>Descripción</label><input value="'+esc(x.nombre||'')+'" oninput="syncMaterials()"></div><div><label>Costo</label><input type="number" min="0" step="0.01" value="'+num(x.costo)+'" oninput="syncMaterials()"></div><button type="button" class="btn danger" onclick="this.parentElement.remove();syncMaterials()">×</button></div>');syncMaterials()};
window.syncMaterials=function(){window.printaMaterials=[...document.querySelectorAll('#materialRows .material-row')].map(r=>({id:r.querySelector('select').value,cantidad:num(r.querySelector('input').value)})).filter(x=>x.id&&x.cantidad>0);window.printaOtherCosts=[...document.querySelectorAll('#otherCostRows .other-row')].map(r=>({nombre:r.querySelectorAll('input')[0].value,costo:num(r.querySelectorAll('input')[1].value)})).filter(x=>x.nombre&&x.costo>=0);const map={};(data.inventory||[]).forEach(x=>map[x.id]=x);const c=window.printaMaterials.reduce((s,x)=>s+num(map[x.id]?.costoUnitario)*x.cantidad,0)+window.printaOtherCosts.reduce((s,x)=>s+x.costo,0),paid=num(document.querySelector('#orderForm [name="pagado"]')?.value);document.querySelector('#orderCostPreview').textContent=money(c);const g=paid-c,p=document.querySelector('#orderProfitPreview');p.textContent=(g>=0?'+':'')+money(g);p.className=g>=0?'gain':'loss'};
const oldOpen=window.openOrder;window.openOrder=function(){oldOpen();installInventoryUI();window.printaMaterials=[];window.printaOtherCosts=[];document.querySelector('#materialRows').innerHTML='';document.querySelector('#otherCostRows').innerHTML='';const f=document.querySelector('#orderForm');const auto=(data.inventory||[]).find(x=>String(x.nombre).toLowerCase()===String(f.elements.producto.value).toLowerCase());if(auto)addMaterialRow({id:auto.id,cantidad:num(f.elements.cantidad.value)||1});syncMaterials()};
const oldEdit=window.editOrder;window.editOrder=function(id){oldEdit(id);installInventoryUI();const o=data.orders.find(x=>x.id===id)||{};window.printaMaterials=parseSafe(o.materialesJson,[]);window.printaOtherCosts=parseSafe(o.otrosCostosJson,[]);document.querySelector('#materialRows').innerHTML='';document.querySelector('#otherCostRows').innerHTML='';window.printaMaterials.forEach(addMaterialRow);window.printaOtherCosts.forEach(addOtherCostRow);syncMaterials()};
function parseSafe(v,f){try{return v?JSON.parse(v):f}catch(e){return f}}
const oldRender=window.render;window.render=function(){oldRender();installInventoryUI();renderInventory()};
setTimeout(()=>{installInventoryUI();renderInventory();const p=document.querySelector('#orderForm [name="pagado"]');if(p)p.addEventListener('input',syncMaterials)},0);
})();</script>`}

function getLogoDataUrl(){try{const b=DriveApp.getFileById(LOGO_FILE_ID).getBlob();return`data:${b.getContentType()};base64,${Utilities.base64Encode(b.getBytes())}`}catch(e){return''}}
function getAppData(){ensureSchema_();const c=CacheService.getScriptCache(),v=c.get(APP_CACHE_KEY);if(v){try{return JSON.parse(v)}catch(e){}}const ss=SpreadsheetApp.openById(SPREADSHEET_ID),orders=readRows_(ss.getSheetByName(ORDERS_SHEET)),expenses=readRows_(ss.getSheetByName(EXPENSES_SHEET)),products=readRows_(ss.getSheetByName(PRODUCTS_SHEET)),inventory=readRows_(ss.getSheetByName(INVENTORY_SHEET)),settings=getSettings_(ss),r={orders,expenses,products,inventory,settings,summary:buildSummary_(orders,expenses)};try{c.put(APP_CACHE_KEY,JSON.stringify(r),120)}catch(e){}return r}
function invalidateCache_(){try{CacheService.getScriptCache().remove(APP_CACHE_KEY)}catch(e){}}
function calculateShippingDate(d,o){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);return addBusinessDays_(parseDate_(d)||new Date(),getHandlingDays_(o,getSettings_(ss)))}

function saveInventoryItem(x){if(!x||!clean_(x.nombre)||number_(x.cantidad,0)<=0)throw new Error('Completa nombre y cantidad.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{ensureSchema_();const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(INVENTORY_SHEET),now=new Date(),id=nextId_('INV'),q=number_(x.cantidad,0),t=money_(x.costoTotal),u=q>0?t/q:0;sh.appendRow([id,clean_(x.nombre),clean_(x.categoria)||'Material',q,t,u,clean_(x.nota),now,now]);invalidateCache_()}finally{lock.releaseLock()}return getAppData()}
function deleteInventoryItem(id){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(INVENTORY_SHEET),used=readRows_(ss.getSheetByName(ORDERS_SHEET)).some(o=>parseJson_(o.materialesJson,[]).some(m=>m.id===id));if(used)throw new Error('Este artículo ya está usado en órdenes. Déjalo en cantidad 0 en vez de borrarlo.');const m=findRowsById_(sh,id);if(m.length===1)sh.deleteRow(m[0]);invalidateCache_()}finally{lock.releaseLock()}return getAppData()}

function saveOrder(o){if(!o||!clean_(o.cliente)||!clean_(o.producto))throw new Error('Completa cliente y producto.');const mode=clean_(o._mode),lock=LockService.getScriptLock();lock.waitLock(30000);try{ensureSchema_();const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(ORDERS_SHEET),now=new Date(),fecha=o.fecha||formatDate_(now),envio=addBusinessDays_(parseDate_(fecha)||now,getHandlingDays_(o.origen,getSettings_(ss)));let id,row=0,created=now,old={};if(mode==='create'){const key=clean_(o.clientKey);id='PC-'+key;if(findRowsById_(sh,id).length===1)return getAppData()}else{id=clean_(o.id);const m=findRowsById_(sh,id);if(m.length!==1)throw new Error('Orden no encontrada.');row=m[0];old=rowObject_(sh,row);created=sh.getRange(row,12).getValue()||now}const mats=parseJson_(o.materialesJson,[]),others=parseJson_(o.otrosCostosJson,[]),cost=calculateCosts_(ss,mats,others,money_(o.pagado)),was=String(old.inventarioDescontado).toLowerCase()==='true';if(was){adjustInventory_(ss,parseJson_(old.materialesJson,[]),1);adjustInventory_(ss,mats,-1)}const values=[id,fecha,o.estado||old.estado||'Pendiente',o.origen||'Otro',clean_(o.cliente),clean_(o.producto),number_(o.cantidad,1),clean_(o.notas),money_(o.pagado),envio,clean_(o.foto),created,now,cost.total,cost.gain,was,JSON.stringify(mats),JSON.stringify(others)];row?sh.getRange(row,1,1,values.length).setValues([values]):sh.appendRow(values);invalidateCache_()}finally{lock.releaseLock()}return getAppData()}
function setOrderStatus(id,status){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(ORDERS_SHEET),m=findRowsById_(sh,id);if(m.length!==1)throw new Error('Orden no encontrada.');const r=m[0],o=rowObject_(sh,r),used=String(o.inventarioDescontado).toLowerCase()==='true',mats=parseJson_(o.materialesJson,[]);if(status==='Listo'&&!used){adjustInventory_(ss,mats,-1);sh.getRange(r,16).setValue(true)}if(status==='Pendiente'&&used){adjustInventory_(ss,mats,1);sh.getRange(r,16).setValue(false)}sh.getRange(r,3).setValue(status);sh.getRange(r,13).setValue(new Date());invalidateCache_()}finally{lock.releaseLock()}return getAppData()}
function deleteOrder(id){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(ORDERS_SHEET),m=findRowsById_(sh,id);if(m.length!==1)throw new Error('Orden no encontrada.');const o=rowObject_(sh,m[0]);if(String(o.inventarioDescontado).toLowerCase()==='true')adjustInventory_(ss,parseJson_(o.materialesJson,[]),1);sh.deleteRow(m[0]);invalidateCache_()}finally{lock.releaseLock()}return getAppData()}

function saveExpense(e){if(!e||money_(e.cantidad)<=0)throw new Error('Escribe una cantidad válida.');const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(EXPENSES_SHEET),now=new Date(),id=e.id||nextId_('GA');upsertById_(sh,id,[id,e.fecha||formatDate_(now),e.categoria||'Otro',clean_(e.lugar),money_(e.cantidad),clean_(e.nota),clean_(e.recibo),e.creadoEn||now]);invalidateCache_();return getAppData()}
function deleteExpense(id){deleteById_(EXPENSES_SHEET,id);invalidateCache_();return getAppData()}
function saveProduct(p){if(!p||!clean_(p.nombre))throw new Error('Escribe el nombre del producto.');const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(PRODUCTS_SHEET),now=new Date(),id=p.id||nextId_('PR');upsertById_(sh,id,[id,clean_(p.nombre),clean_(p.foto),String(p.disponible)!=='false',p.creadoEn||now,now]);invalidateCache_();return getAppData()}
function deleteProduct(id){deleteById_(PRODUCTS_SHEET,id);invalidateCache_();return getAppData()}
function uploadFile(fileData,fileName,mimeType,ownerId,category){if(!fileData)return'';const bytes=Utilities.base64Decode(String(fileData).split(',').pop()),safe=`${ownerId||'GENERAL'}_${category||'archivo'}_${Date.now()}_${fileName||'archivo'}`,f=getUploadsFolder_().createFile(Utilities.newBlob(bytes,mimeType||'application/octet-stream',safe));f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return f.getUrl()}
function getUploadsFolder_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(CONFIG_SHEET),v=sh.getRange(1,1,Math.max(sh.getLastRow(),1),2).getValues();let id='',row=0;v.forEach((x,i)=>{if(x[0]==='CARPETA_FOTOS_ID'){id=x[1];row=i+1}});if(id){try{return DriveApp.getFolderById(id)}catch(e){}}const f=DriveApp.createFolder('PRINTA - Fotos y recibos');if(row)sh.getRange(row,2).setValue(f.getId());return f}

function ensureSchema_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);ensureSheet_(ss,ORDERS_SHEET,ORDER_HEADERS);ensureSheet_(ss,EXPENSES_SHEET,EXPENSE_HEADERS);ensureSheet_(ss,PRODUCTS_SHEET,PRODUCT_HEADERS);ensureSheet_(ss,CONFIG_SHEET,['CLAVE','VALOR']);ensureSheet_(ss,INVENTORY_SHEET,INVENTORY_HEADERS)}
function ensureSheet_(ss,n,h){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(h);else{const cur=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),1)).getDisplayValues()[0];h.forEach(x=>{if(!cur.includes(x)){sh.getRange(1,sh.getLastColumn()+1).setValue(x);cur.push(x)}})}return sh}
function calculateCosts_(ss,mats,others,paid){const inv=readRows_(ss.getSheetByName(INVENTORY_SHEET)),map={};inv.forEach(x=>map[x.id]=x);let total=0;mats.forEach(m=>{if(map[m.id])total+=money_(map[m.id].costoUnitario)*number_(m.cantidad,0)});total+=others.reduce((s,x)=>s+money_(x.costo),0);return{total,gain:paid-total}}
function adjustInventory_(ss,mats,dir){const sh=ss.getSheetByName(INVENTORY_SHEET),map={};readRows_(sh).forEach(x=>map[x.id]=x);mats.forEach(m=>{const x=map[m.id];if(!x)throw new Error('Material no encontrado.');const rows=findRowsById_(sh,m.id),q=number_(m.cantidad,0),current=number_(x.cantidad,0),next=current+dir*q;if(next<0)throw new Error('Inventario insuficiente de '+x.nombre+'. Disponible: '+current);sh.getRange(rows[0],4).setValue(next);sh.getRange(rows[0],5).setValue(next*money_(x.costoUnitario));sh.getRange(rows[0],9).setValue(new Date())})}
function getSettings_(ss){const sh=ss.getSheetByName(CONFIG_SHEET),rows=sh.getRange(1,1,Math.max(sh.getLastRow(),1),2).getValues(),o={tiktokDays:2,printaDays:3};rows.forEach(r=>{if(r[0]==='TIKTOK_DIAS_ENVIO')o.tiktokDays=number_(r[1],2);if(r[0]==='PRINTA_DIAS_ENVIO')o.printaDays=number_(r[1],3)});return o}
function getHandlingDays_(o,s){return o==='TikTok'?s.tiktokDays:s.printaDays}function addBusinessDays_(d,n){const x=new Date(d);let a=0;while(a<n){x.setDate(x.getDate()+1);if(x.getDay()!==0&&x.getDay()!==6)a++}return formatDate_(x)}function parseDate_(v){if(!v)return null;const p=String(v).split('-').map(Number);return p.length===3?new Date(p[0],p[1]-1,p[2],12):new Date(v)}
function readRows_(sh){if(!sh||sh.getLastRow()<2)return[];const v=sh.getRange(1,1,sh.getLastRow(),sh.getLastColumn()).getDisplayValues(),h=v.shift();return v.filter(r=>r[0]).map(r=>{const o={};h.forEach((x,i)=>o[toKey_(x)]=r[i]);return o})}function rowObject_(sh,r){const h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],v=sh.getRange(r,1,1,sh.getLastColumn()).getDisplayValues()[0],o={};h.forEach((x,i)=>o[toKey_(x)]=v[i]);return o}
function buildSummary_(o,e){const m=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM'),mo=o.filter(x=>String(x.fecha||'').startsWith(m)),me=e.filter(x=>String(x.fecha||'').startsWith(m)),ing=mo.reduce((s,x)=>s+money_(x.pagado),0),cost=mo.reduce((s,x)=>s+money_(x.costoTotal),0),gas=me.reduce((s,x)=>s+money_(x.cantidad),0);return{pendientes:o.filter(x=>x.estado==='Pendiente').length,listos:o.filter(x=>x.estado==='Listo').length,ingresos:ing,costos:cost,gastos:gas,ganancia:ing-cost-gas}}
function upsertById_(sh,id,row){const m=findRowsById_(sh,id);m.length===1?sh.getRange(m[0],1,1,row.length).setValues([row]):sh.appendRow(row)}function deleteById_(n,id){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n),m=findRowsById_(sh,id);if(m.length===1)sh.deleteRow(m[0])}function findRowsById_(sh,id){if(!sh||sh.getLastRow()<2)return[];const v=sh.getRange(2,1,sh.getLastRow()-1,1).getDisplayValues(),r=[];v.forEach((x,i)=>{if(clean_(x[0])===clean_(id))r.push(i+2)});return r}function parseJson_(v,f){try{return v?JSON.parse(v):f}catch(e){return f}}function nextId_(p){return p+'-'+Utilities.getUuid().replace(/-/g,'').toUpperCase()}function formatDate_(d){return Utilities.formatDate(d,'America/New_York','yyyy-MM-dd')}function money_(v){const n=Number(String(v||0).replace(/[^0-9.-]/g,''));return isNaN(n)?0:n}function number_(v,f){const n=Number(v);return isNaN(n)?f:n}function clean_(v){return String(v==null?'':v).trim()}function toKey_(h){return String(h).toLowerCase().replace(/_([a-z])/g,(_,c)=>c.toUpperCase())}
