from pathlib import Path

p=Path('App.html')
s=p.read_text(encoding='utf-8')

old="""async function saveOrderClient(e){e.preventDefault();const f=e.target,b=$('#saveOrderBtn'),o=Object.fromEntries(new FormData(f).entries()),isEdit=!!o.id;o._mode=isEdit?'edit':'create';o.clientKey=isEdit?'':'CLIENT-'+Date.now()+'-'+Math.random().toString(36).slice(2,10);const all=mainMaterial?[mainMaterial,...materials]:materials,costs=[...otherCosts];if(inkType!=='Sin tinta'||num(inkCost)>0)costs.push({nombre:'Tinta '+inkType,costo:num(inkCost),tipoCosto:'tinta',tintaTipo:inkType});o.materialesJson=JSON.stringify(all);o.otrosCostosJson=JSON.stringify(costs);setSpin(b,true);try{const old=String(o.foto||'').split('|||').filter(Boolean),fresh=[];for(const file of pendingFiles)fresh.push(await upload(file,o.id||o.clientKey,'orden'));o.foto=[...old,...fresh].join('|||');google.script.run.withSuccessHandler(d=>{data=d;setSpin(b,false);renderAll();closeModal('orderModal')}).withFailureHandler(x=>{setSpin(b,false);showError('orderError',x)}).saveOrder(o)}catch(x){setSpin(b,false);showError('orderError',x)}}"""
new="""async function saveOrderClient(e){e.preventDefault();const f=e.target,b=$('#saveOrderBtn'),start=Date.now(),o=Object.fromEntries(new FormData(f).entries()),isEdit=!!o.id;o._mode=isEdit?'edit':'create';o.clientKey=isEdit?'':'CLIENT-'+Date.now()+'-'+Math.random().toString(36).slice(2,10);const all=mainMaterial?[mainMaterial,...materials]:materials,costs=[...otherCosts];if(inkType!=='Sin tinta'||num(inkCost)>0)costs.push({nombre:'Tinta '+inkType,costo:num(inkCost),tipoCosto:'tinta',tintaTipo:inkType});o.materialesJson=JSON.stringify(all);o.otrosCostosJson=JSON.stringify(costs);setSpin(b,true);setTimeout(()=>closeModal('orderModal'),500);try{const old=String(o.foto||'').split('|||').filter(Boolean),fresh=[];for(const file of pendingFiles)fresh.push(await upload(file,o.id||o.clientKey,'orden'));o.foto=[...old,...fresh].join('|||');google.script.run.withSuccessHandler(async d=>{await waitMin(start,500);data=d;pendingFiles=[];renderAll()}).withFailureHandler(async x=>{await waitMin(start,500);setSpin(b,false);showModal('orderModal');showError('orderError',x)}).saveOrder(o)}catch(x){await waitMin(start,500);setSpin(b,false);showModal('orderModal');showError('orderError',x)}}"""
if old in s:s=s.replace(old,new,1)

old="""function saveInventoryClient(e){e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f).entries());if(o.categoria==='Producto'){o.nombre=o.productoRelacionado;if(!o.nombre)return showError('inventoryError','Selecciona el tipo de producto.')}busy(f,true);google.script.run.withSuccessHandler(d=>{data=d;busy(f,false);renderAll();closeModal('inventoryModal')}).withFailureHandler(x=>{busy(f,false);showError('inventoryError',x)}).saveInventoryItem(o)}"""
new="""function saveInventoryClient(e){e.preventDefault();const f=e.target,b=f.querySelector('button[type=submit],button:not([type])'),start=Date.now(),o=Object.fromEntries(new FormData(f).entries());if(o.categoria==='Producto'){o.nombre=o.productoRelacionado;if(!o.nombre)return showError('inventoryError','Selecciona el tipo de producto.')}setSpin(b,true);setTimeout(()=>closeModal('inventoryModal'),500);google.script.run.withSuccessHandler(async d=>{await waitMin(start,500);data=d;renderAll()}).withFailureHandler(async x=>{await waitMin(start,500);setSpin(b,false);showModal('inventoryModal');showError('inventoryError',x)}).saveInventoryItem(o)}"""
if old in s:s=s.replace(old,new,1)

old="""async function saveExpenseClient(e){e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f).entries());busy(f,true);if($('#receiptFile').files[0])o.recibo=await upload($('#receiptFile').files[0],'GASTO','recibo');google.script.run.withSuccessHandler(d=>{data=d;busy(f,false);renderAll();closeModal('expenseModal')}).withFailureHandler(x=>{busy(f,false);showError('expenseError',x)}).saveExpense(o)}"""
new="""async function saveExpenseClient(e){e.preventDefault();const f=e.target,b=f.querySelector('button[type=submit],button:not([type])'),start=Date.now(),o=Object.fromEntries(new FormData(f).entries());setSpin(b,true);setTimeout(()=>closeModal('expenseModal'),500);try{if($('#receiptFile').files[0])o.recibo=await upload($('#receiptFile').files[0],'GASTO','recibo');google.script.run.withSuccessHandler(async d=>{await waitMin(start,500);data=d;renderAll()}).withFailureHandler(async x=>{await waitMin(start,500);setSpin(b,false);showModal('expenseModal');showError('expenseError',x)}).saveExpense(o)}catch(x){await waitMin(start,500);setSpin(b,false);showModal('expenseModal');showError('expenseError',x)}}"""
if old in s:s=s.replace(old,new,1)

old="""async function saveProductClient(e){e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f).entries());busy(f,true);if($('#productImage').files[0])o.foto=await upload($('#productImage').files[0],o.id||'PRODUCTO','producto');google.script.run.withSuccessHandler(d=>{data=d;busy(f,false);renderAll();closeModal('productModal')}).withFailureHandler(x=>{busy(f,false);showError('productError',x)}).saveProduct(o)}"""
new="""async function saveProductClient(e){e.preventDefault();const f=e.target,b=f.querySelector('button[type=submit],button:not([type])'),start=Date.now(),o=Object.fromEntries(new FormData(f).entries());setSpin(b,true);setTimeout(()=>closeModal('productModal'),500);try{if($('#productImage').files[0])o.foto=await upload($('#productImage').files[0],o.id||'PRODUCTO','producto');google.script.run.withSuccessHandler(async d=>{await waitMin(start,500);data=d;renderAll()}).withFailureHandler(async x=>{await waitMin(start,500);setSpin(b,false);showModal('productModal');showError('productError',x)}).saveProduct(o)}catch(x){await waitMin(start,500);setSpin(b,false);showModal('productModal');showError('productError',x)}}"""
if old in s:s=s.replace(old,new,1)

p.write_text(s,encoding='utf-8')
